name: senioren_app
description: "Seniorenfreundliche Begleit-App mit Check-in und Assistent"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.4
  firebase_app_check: ^0.1.5+1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.3
  intl: ^0.18.1
  collection: ^1.18.0
  uuid: ^4.2.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.3
  go_router: ^13.1.0
  material_design_icons_flutter: ^7.0.7296
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  flutter_tts: ^3.8.0
  speech_to_text: ^7.0.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  firebase_tools:
    hosted:
      name: firebase_tools
      url: https://pub.dev
      version: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true
