name: senioren_app
description: "Seniorenfreundliche Begleit-App mit Check-in und Assistent"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1

  # Firebase – zueinander passende Versionen
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_app_check: ^0.2.2+7
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^16.3.3

  # Utils/UI
  intl: ^0.20.2
  collection: ^1.19.1
  uuid: ^4.5.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  go_router: ^13.2.5
  material_design_icons_flutter: ^7.0.7296
  flex_color_scheme: ^8.3.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  permission_handler: ^11.4.0
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.2
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true
